### ISSUE TITLE
[BUG] Config save crash

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#103]
**Describe the bug**  
Saving a config with "?<>" in the name crashes the game (using "!;.,-_°()^@" is fine and the config get saved)

**To Reproduce**  
1. Save a config with "?<>" in the name

**Expected behavior**  
Maybe an error message or just saving the config without the symbols

**Crashlog**  
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/19/22 3:55 PM
Description: Updating screen events

java.nio.file.InvalidPathException: Illegal char <?> at index 23: earthhack\modules\ccdef??.json
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.save(AbstractConfigHelper.java:140)
	at me.earth.earthhack.impl.managers.config.ConfigManager$$Lambda$647/280725600.accept(Unknown Source)
	at me.earth.earthhack.impl.managers.config.ConfigManager.execute(ConfigManager.java:99)
	at me.earth.earthhack.impl.managers.config.ConfigManager.save(ConfigManager.java:69)
	at me.earth.earthhack.impl.commands.ConfigCommand.lambda$execute$2(ConfigCommand.java:229)
	at me.earth.earthhack.impl.commands.ConfigCommand$$Lambda$643/780838526.run(Unknown Source)
	at me.earth.earthhack.impl.commands.ConfigCommand.lambda$null$4(ConfigCommand.java:424)
	at me.earth.earthhack.impl.commands.ConfigCommand$$Lambda$645/1078081948.func_73878_a(Unknown Source)
	at net.minecraft.client.gui.GuiYesNo.func_146284_a(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.save(AbstractConfigHelper.java:140)
	at me.earth.earthhack.impl.managers.config.ConfigManager$$Lambda$647/280725600.accept(Unknown Source)
	at me.earth.earthhack.impl.managers.config.ConfigManager.execute(ConfigManager.java:99)
	at me.earth.earthhack.impl.managers.config.ConfigManager.save(ConfigManager.java:69)
	at me.earth.earthhack.impl.commands.ConfigCommand.lambda$execute$2(ConfigCommand.java:229)
	at me.earth.earthhack.impl.commands.ConfigCommand$$Lambda$643/780838526.run(Unknown Source)
	at me.earth.earthhack.impl.commands.ConfigCommand.lambda$null$4(ConfigCommand.java:424)
	at me.earth.earthhack.impl.commands.ConfigCommand$$Lambda$645/1078081948.func_73878_a(Unknown Source)
	at net.minecraft.client.gui.GuiYesNo.func_146284_a(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiChatOF

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ai_2473'/156, l='MpServer', x=675.93, y=69.00, z=1699.56]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,156), Chunk: (at 4,4,12 in 15,9; contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 137047 game time, 15600 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Ai_2473'/156, l='MpServer', x=675.93, y=69.00, z=1699.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 541870520 bytes (516 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.100.9805' Renderer: 'Intel(R) Iris(R) Xe Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 30.0.100.9805, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: rlFurfSky_6lReborn_8lFL_8l71.48l.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9805
	OpenGlRenderer: Intel(R) Iris(R) Xe Graphics
	OpenGlVendor: Intel
	CpuCount: 8
```

**Additional context**  
I was using Optifine but I think it doesn't matter

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.
- [x] 3arthqu4ke on top

**Comment by 3arthqu4ke** [comment]
I will fix this sometime™ but I think that problem might occur at multiple points in the client and I do not have too much time atm :(

**Comment by Ai2473** [comment]
It's ok np

**Comment by GurteX** [comment]
erthquke cant
