### ISSUE TITLE
[BUG] Lambda compatibility issue with 3arthh4ck 1.8.5

### ISSUE THREAD

**Issue by Ai2473** [3arthqu4ke/3arthh4ck#296]
**Describe the bug**  
Generating a singleplayer world/joining a server cause the game to crash

**To Reproduce**  
1. Open minecraft with forge, loading in lambda and latest 3arthh4ck 1.8.5
2. Join a server/singleplayer 
3. At the `loading...` the game idle for a bit (my hardware issue??) and crashes
4. Error

**Crashlog**  
## Exit error (server join, no crashlog): 
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```
Exit code -1

## Singleplayer generating a world crashlog:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (lambda-3.0.1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/24/22 10:25 AM
Description: Ticking entity

java.lang.IncompatibleClassChangeError: Expected static field net.minecraft.block.Block.mc
	at net.minecraft.block.Block.handler$getCollisionBoundingBoxHook$zfh000(Block.java:4230)
	at net.minecraft.block.Block.func_180646_a(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:448)
	at net.minecraft.block.Block.func_185477_a(Block.java:460)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1341)
	at net.minecraft.world.World.func_184143_b(World.java:1429)
	at net.minecraft.entity.Entity.func_145771_j(Entity.java:2379)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:119)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.Block.handler$getCollisionBoundingBoxHook$zfh000(Block.java:4230)
	at net.minecraft.block.Block.func_180646_a(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:448)
	at net.minecraft.block.Block.func_185477_a(Block.java:460)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1341)
	at net.minecraft.world.World.func_184143_b(World.java:1429)
	at net.minecraft.entity.Entity.func_145771_j(Entity.java:2379)
	at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:119)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 0
	Entity Name: item.tile.woolCarpet.lime
	Entity's Exact location: 959.10, 4.00, -343.78
	Entity's Block location: World: (959,4,-344), Chunk: (at 15,0,8 in 59,-22; contains blocks 944,0,-352 to 959,255,-337), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2819889651067285911
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1012,4,-432), Chunk: (at 4,0,0 in 63,-27; contains blocks 1008,0,-432 to 1023,255,-417), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 39413 game time, 39413 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 103850 (now: false), thunder time: 62359 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 765919400 bytes (730 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lambda    | 3.0.1        | lambda-3.0.1.jar              | None                                     |

	Loaded coremods (and transformers): 
LambdaCoreMod (lambda-3.0.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9805
	OpenGlRenderer: Intel(R) Iris(R) Xe Graphics
	OpenGlVendor: Intel
	CpuCount: 8
```
## Singleplayer joining an already generated world crashlog:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LambdaCoreMod (lambda-3.0.1.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 9/24/22 10:28 AM
Description: Ticking entity

java.lang.IncompatibleClassChangeError: Expected static field net.minecraft.block.Block.mc
	at net.minecraft.block.Block.handler$getCollisionBoundingBoxHook$zfh000(Block.java:4230)
	at net.minecraft.block.Block.func_180646_a(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:448)
	at net.minecraft.block.Block.func_185477_a(Block.java:460)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1341)
	at net.minecraft.world.World.func_184144_a(World.java:1365)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:721)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityRabbit.func_70636_d(EntityRabbit.java:274)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.Block.handler$getCollisionBoundingBoxHook$zfh000(Block.java:4230)
	at net.minecraft.block.Block.func_180646_a(Block.java)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:448)
	at net.minecraft.block.Block.func_185477_a(Block.java:460)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:453)
	at net.minecraft.world.World.func_191504_a(World.java:1341)
	at net.minecraft.world.World.func_184144_a(World.java:1365)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:721)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.EntityRabbit.func_70636_d(EntityRabbit.java:274)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:rabbit (net.minecraft.entity.passive.EntityRabbit)
	Entity ID: 25
	Entity Name: Rabbit
	Entity's Exact location: -146.50, 67.00, 127.50
	Entity's Block location: World: (-147,67,127), Chunk: (at 13,4,15 in -10,7; contains blocks -160,0,112 to -145,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2333891260526399362
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (4,64,252), Chunk: (at 4,4,12 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 39503 game time, 39503 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 108420 (now: false), thunder time: 86717 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 856502152 bytes (816 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lambda    | 3.0.1        | lambda-3.0.1.jar              | None                                     |

	Loaded coremods (and transformers): 
LambdaCoreMod (lambda-3.0.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9805
	OpenGlRenderer: Intel(R) Iris(R) Xe Graphics
	OpenGlVendor: Intel
	CpuCount: 8
```

**Additional context**  
Using I'm using optifine, vanilla launcher (old one, not xbox), and lambda 3.0.1 (not the latest, i don't think this is the issue)

**Bug investigation**
I've done some investigation and the issue seems to be between [101f91e](https://github.com/3arthqu4ke/3arthh4ck/commit/101f91eb47c0afea0fb0865c0b4835102063ab15) (still working here) and [0792926](https://github.com/3arthqu4ke/3arthh4ck/commit/07929269b58ec3f1ecd2379a279e6e8965fe14b4) (no more working here and after here)

**Checklist**
- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by 3arthqu4ke** [comment]
Can you try this version? https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3117824307/jobs/5056725493
Also can you tell me if the new Jesus works for you normally and on entities?

**Comment by Ai2473** [comment]
>  Also can you tell me if the new Jesus works for you normally and on entities?
Normally yes, for entities I'm currently making some tests, nvm i saw that before :)

**Comment by Ai2473** [comment]
> Can you try this version? https://github.com/3arthqu4ke/3arthh4ck/actions/runs/3117824307/jobs/5056725493

Works perfectly

**Comment by Ai2473** [comment]
btw I saw that in the 1.8.5 pull request, there is automatic merging with 1 review and I can review xd


Also could you link me some stuff on where to get started with mc clients? (I would really like to help you, but idk where to start)
