### ISSUE TITLE
[BUG] my game crashes

### ISSUE THREAD

**Issue by shasdfasdqw** [3arthqu4ke/3arthh4ck#307]
i didn't understand how to make macros in the game, so i was doing it in notepad
i made a mistake somewhere and I don't understand my game crashes
and i tried to do it by looking here
https://github.com/3arthqu4ke/3arthh4ck/blob/c949bf816979c1511706803c2b66a9029c52f1db/configs/macros/ongroundconfig.json

Macro
{
  "surround1": {
    "bind": "V",
    "type": "NORMAL",
    "release": false,
    "command": "speed enabled false"
  },
  "surround2": {
    "bind": "V",
    "type": "NORMAL",
    "release": false,
    "command": "step enabled false"
  },
  "Protection": {
    "bind": "NONE",
    "type": "DELEGATE",
    "command": "+autoarmor mode protection",
  },
  "BlastPro": {
    "bind": "NONE",
    "type": "DELEGATE",
    "command": "+autoarmor mode blast",
	},
  "BlastAndProtect": {
    "bind": "L",
    "type": "FLOW",
    "release": false,
    "command": "macro use Protection",
    "command1": "macro use BlastPro"
  }
}

CrashLog

// Sorry :(

Time: 9/25/22 12:12 PM
Description: Initializing game

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 18 column 4 path $.Protection.command
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:47)
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:14)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.read(AbstractConfigHelper.java:210)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.lambda$refresh$0(AbstractConfigHelper.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.refresh(AbstractConfigHelper.java:93)
	at me.earth.earthhack.impl.managers.config.ConfigManager.refreshAll(ConfigManager.java:52)
	at me.earth.earthhack.impl.managers.Managers.load(Managers.java:118)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:30)
	at bib.handler$initHook$zzi000(SourceFile:3117)
	at bib.aq(SourceFile:556)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 18 column 4 path $.Protection.command
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:47)
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:14)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.read(AbstractConfigHelper.java:210)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.lambda$refresh$0(AbstractConfigHelper.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.refresh(AbstractConfigHelper.java:93)
	at me.earth.earthhack.impl.managers.config.ConfigManager.refreshAll(ConfigManager.java:52)
	at me.earth.earthhack.impl.managers.Managers.load(Managers.java:118)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:30)
	at bib.handler$initHook$zzi000(SourceFile:3117)
	at bib.aq(SourceFile:556)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_345, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 399250384 bytes (380 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-OptiFine_HD_U_G5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: DreamEscape
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E4600 @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 5450
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by 3arthqu4ke** [comment]
Intellij has json syntax highlighting or [this](https://jsonformatter.curiousconcept.com/#) tool removes the commas.

It already tells you that it tries to find something in line 18 thats not there, so we check line 17:
```json
{
  "surround1": {
    "bind": "V",
    "type": "NORMAL",
    "release": false,
    "command": "speed enabled false"
  },
  "surround2": {
    "bind": "V",
    "type": "NORMAL",
    "release": false,
    "command": "step enabled false"
  },
  "Protection": {
    "bind": "NONE",
    "type": "DELEGATE",
    "command": "+autoarmor mode protection", <- line 17: this comma is wrong
  },
  "BlastPro": {
    "bind": "NONE",
    "type": "DELEGATE",
    "command": "+autoarmor mode blast", <- this comma is wrong
  },
  "BlastAndProtect": {
    "bind": "L",
    "type": "FLOW",
    "release": false,
    "command": "macro use Protection",
    "command1": "macro use BlastPro"
  }
}
```

**Comment by shasdfasdqw** [comment]
oh thanks

**Comment by 3arthqu4ke** [comment]
In game the commands would be 
```
+macro add blastpro NONE autoarmor mode blast
+macro add prot NONE autoarmor mode protection
+macro add BlastAndProtect L flow blastpro prot 
```

**Comment by shasdfasdqw** [comment]
thanks
