### ISSUE TITLE
[BUG] Announcer crash randomly

### ISSUE THREAD

**Issue by GRIFFiin** [3arthqu4ke/3arthh4ck#331]
**Describe the bug**  
Announcer can crash you randomly if  you killed someone

**To Reproduce**  
1. activate announcer'
2. kill lots of ppl
3. See error

**Crashlog**  
[17:37:23] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_51]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_51]
	at me.earth.earthhack.impl.modules.misc.announcer.ListenerDeath.invoke(ListenerDeath.java:36) ~[ListenerDeath.class:?]
	at me.earth.earthhack.impl.modules.misc.announcer.ListenerDeath.invoke(ListenerDeath.java:11) ~[ListenerDeath.class:?]
	at me.earth.earthhack.api.event.bus.SimpleBus.post(SimpleBus.java:37) ~[SimpleBus.class:?]
	at net.minecraft.entity.EntityLivingBase.handler$notifyDataManagerChangeHook$zhf000(EntityLivingBase.java:4398) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184206_a(EntityLivingBase.java:2744) ~[vp.class:?]
	at net.minecraft.network.datasync.EntityDataManager.func_187218_a(EntityDataManager.java:319) ~[nb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147284_a(NetHandlerPlayClient.java:546) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketEntityMetadata.func_148833_a(SourceFile:42) ~[kd.class:?]
	at net.minecraft.network.play.server.SPacketEntityMetadata.func_148833_a(SourceFile:11) ~[kd.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 9 more

**Comment by AlexanderJonny** [comment]
Finally someone sends this question, I always thought it was my own problem
After I open announcer and kill the player, my game becomes stationary and when I try to quit the server, my client crashes
