### ISSUE TITLE
[BUG] java.lang.UnsatisfiedLinkError: no jassimp in java.library.path

### ISSUE THREAD

**Issue by razedftw** [3arthqu4ke/3arthh4ck#6]
![unknown (7)](https://user-images.githubusercontent.com/76087660/163681466-d3b95a81-e196-4178-8746-8e7aed9056c2.png)

Every time I build phobos and launch it I get this crash error 

java.lang.UnsatisfiedLinkError: no jassimp in java.library.path

**Comment by lyricnight** [comment]
do you have ModelTotem on? That happens to me whenever I use it

**Comment by razedftw** [comment]
> do you have ModelTotem on? That happens to me whenever I use it. Just turn it off on your config and it should launch fine

nah It just happens when I launch it

**Comment by master7720** [comment]
i know how to fix it add a default config into modules then add your config(change the name) then go into any servers and type +config module load yourconfigname

**Comment by master7720** [comment]
did this work @razedftw

**Comment by razedftw** [comment]
> did this work @razedftw 

I haven't tried it yet i'm not home

**Comment by master7720** [comment]
kk it worked for me

**Comment by razedftw** [comment]
> kk it worked for me

I got home and I couldnt like even launch it so I couldnt try it

**Comment by master7720** [comment]
> > kk it worked for me
> 
> I got home and I couldnt like even launch it so I couldnt try it

if it doesnt work add me on discord NotRockysAly#6534

**Comment by threevt** [comment]
Send full crash log

**Comment by razedftw** [comment]
> Send full crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/16/22 10:44 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: no jassimp in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jassimp.JassimpLibraryLoader.loadLibrary(JassimpLibraryLoader.java:63)
	at jassimp.Jassimp.loadLibrary(Jassimp.java:317)
	at jassimp.Jassimp.importFile(Jassimp.java:124)
	at jassimp.Jassimp.importFile(Jassimp.java:108)
	at me.earth.earthhack.impl.util.render.model.ModelUtil.loadModel(ModelUtil.java:123)
	at me.earth.earthhack.impl.managers.client.FileManager.handleModelDir(FileManager.java:146)
	at me.earth.earthhack.impl.managers.client.FileManager.init(FileManager.java:73)
	at me.earth.earthhack.impl.managers.client.FileManager.<init>(FileManager.java:47)
	at me.earth.earthhack.impl.managers.Managers.<clinit>(Managers.java:78)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:29)
	at net.minecraft.client.Minecraft.handler$initHook2$zzk000(Minecraft.java:3507)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jassimp.JassimpLibraryLoader.loadLibrary(JassimpLibraryLoader.java:63)
	at jassimp.Jassimp.loadLibrary(Jassimp.java:317)
	at jassimp.Jassimp.importFile(Jassimp.java:124)
	at jassimp.Jassimp.importFile(Jassimp.java:108)
	at me.earth.earthhack.impl.util.render.model.ModelUtil.loadModel(ModelUtil.java:123)
	at me.earth.earthhack.impl.managers.client.FileManager.handleModelDir(FileManager.java:146)
	at me.earth.earthhack.impl.managers.client.FileManager.init(FileManager.java:73)
	at me.earth.earthhack.impl.managers.client.FileManager.<init>(FileManager.java:47)
	at me.earth.earthhack.impl.managers.Managers.<clinit>(Managers.java:78)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:29)
	at net.minecraft.client.Minecraft.handler$initHook2$zzk000(Minecraft.java:3507)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by 3arthqu4ke** [comment]
Looking into it. Could someone provide me with a simple 3d model to test the model totem?

**Comment by 3arthqu4ke** [comment]
For now just clear earthhack/models

**Comment by Sandwich4780** [comment]
> Looking into it. Could someone provide me with a simple 3d model to test the model totem?
[zero-two.zip](https://github.com/3arthqu4ke/3arthh4ck/files/8502277/zero-two.zip)
Not sure if that will work but it was the only one I could find.

**Comment by 3arthqu4ke** [comment]
@Sandwich4780 ty, worked

Should be fixed, you can find a jar [here](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2181044856).
In the future the model stuff might get moved to plugin as it bloats the jar quite a bit.

I'll leave this open for a bit, if you have problems or if it works please tell me here.

**Comment by razedftw** [comment]
> @Sandwich4780 ty, worked
> 
> Should be fixed, you can find a jar [here](https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2181044856). In the future the model stuff might get moved to plugin as it bloats the jar quite a bit.
> 
> I'll leave this open for a bit, if you have problems or if it works please tell me here.

I get a dif error this time launching it 

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/17/22 7:15 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:37)
	at net.minecraft.client.Minecraft.handler$initHook2$zzk000(Minecraft.java:3507)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at me.earth.earthhack.impl.util.render.model.ModelUtil.loadModel(ModelUtil.java:125)
	at me.earth.earthhack.impl.managers.client.FileManager.handleModelDir(FileManager.java:146)
	at me.earth.earthhack.impl.managers.client.FileManager.init(FileManager.java:73)
	at me.earth.earthhack.impl.managers.client.FileManager.<init>(FileManager.java:47)
	at me.earth.earthhack.impl.managers.Managers.<clinit>(Managers.java:78)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:37)
	at net.minecraft.client.Minecraft.handler$initHook2$zzk000(Minecraft.java:3507)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by iJese-New** [comment]
i cant open the mc
