### ISSUE TITLE
[BUG] Crash with future

### ISSUE THREAD

**Issue by iJese-New** [3arthqu4ke/3arthh4ck#62]
Some time ago I was able to use 3arth and future, but it crashed and since then I haven't been able to use it anymore

I already deleted the "earthhack" folder

I already tried it with "-noverify"

I await your response thanks.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/7/22 11:40 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at me.earth.earthhack.impl.managers.chat.CommandManager.init(CommandManager.java:100)
	at me.earth.earthhack.impl.managers.Managers.load(Managers.java:80)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:27)
	at net.minecraft.client.Minecraft.handler$zzl000$initHook2(Minecraft.java:44655)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.network.PacketBuffer.constant$zjd000$f$I(PacketBuffer.java:47180)
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315)
	at net.minecraft.network.PacketBuffer.func_150791_c(PacketBuffer.java:361)
	at me.earth.earthhack.impl.commands.KitCommand.<clinit>(KitCommand.java:249)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.earth.earthhack.impl.managers.chat.CommandManager.init(CommandManager.java:100)
	at me.earth.earthhack.impl.managers.Managers.load(Managers.java:80)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:27)
	at net.minecraft.client.Minecraft.handler$zzl000$initHook2(Minecraft.java:44655)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 760641904 bytes (725 MB) / 1845493760 bytes (1760 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by 3arthqu4ke** [comment]
This is an issue on Futures end. Fortunately, because most people don't have that problem it might be one of Futures modules so if you find it you can turn it off.

**Comment by 3arthqu4ke** [comment]
Fine, while I hope they fix it here's a fix that will make you not crash but breaks the KitCommand: https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2287200703

**Comment by iJese-New** [comment]
thanks
